//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int id_prestamo { get; set; }
        public Nullable<int> cod_socio { get; set; }
        public Nullable<int> n_copia { get; set; }
        public string tipo_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public Nullable<System.DateTime> fecha_tope { get; set; }
    
        public virtual Copias Copias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
